version: '3.9'

services:
  frontend:
    image: julianlechner/ecommerce-frontend
    ports:
      - "80:80"

  backend:
    image: julianlechner/ecommerce-backend
    ports:
      - "8000:8000"
    volumes:
      - "~/apps/backend:/var/lib/backend/data"
    
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - "~/apps/postgres:/var/lib/postgresql/data"
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    env_file:
      - ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}        
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - "~/apps/pgadmin:/var/lib/pgadmin" # Persist PGAdmin data